#!/usr/bin/env ruby

require 'yaml'
require 'puppet'

puppet_base = "https://puppet:8140"
path="/production/facts_search/search?facts.memorysize.ge=64"

cmd = "curl -s -k -H \"Accept: yaml\" #{puppet_base}#{path}"
ans = %x[#{cmd}]
nodes = YAML::load(ans)
node_array = []
nodes.each do |node|
	node_url="https://puppet:8140/production/facts/#{node}"
	node_cmd="curl -s -k -H \"Accept: yaml\" #{node_url}"
	node_ans= %x[#{node_cmd}]
	node_array << YAML::load(node_ans)
end
node_array.each do |node|
	name = node.name
	facts = node.values
	ram=facts['memorysize']
	procs=facts['processorcount']

	puts "#{name} RAM: #{ram} ProcessorCores: #{procs}"

end
