#!/usr/bin/env ruby

require 'yaml'
require 'puppet'

puts "Welcome to the Compute Finder script!"
puts "This script aims to help you locate compute nodes based on simple requirements"
puts "Such as the minimum amount of RAM or # of processor cores"
puts "---"
puts "---"
puts "What minimum amount of ram would you like?"
puts "(in GB, leave blank for no minimum)"
mem=gets.chomp
puts "What minimum number of processor cores would you like?"
puts "(leave blank for no minimum)"
procs=gets.chomp

sleep 1

search ="facts.compute_node=true"
if mem != ""
	search << "&facts.memorysize.ge=#{mem}"
end

if procs !=""
	search << "&facts.processorcount.ge=#{procs}"
end

puppet_base = "https://puppet:8140"
path="/production/facts_search/search?"


puts "Finding matching nodes, please wait..."
cmd = "curl -s -k -H \"Accept: yaml\" \"#{puppet_base}#{path}#{search}\""
ans = %x[#{cmd}]
nodes = YAML::load(ans)
node_array = []
nodes.each do |node|
	node_url="https://puppet:8140/production/facts/#{node}"
	node_cmd="curl -s -k -H \"Accept: yaml\" #{node_url}"
	node_ans= %x[#{node_cmd}]
	node_array << YAML::load(node_ans)
end

results =[]
node_array.each do |node|
	name = node.name
	facts = node.values
	ram=facts['memorysize']
	procs=facts['processorcount']
	results.push("Host: #{name} RAM: #{ram} ProcessorCores: #{procs}")
end
results.sort!
puts results
