#!/usr/bin/env ruby
require 'yaml'
puppet_base = "https://puppet:8140"
path="/production/facts_search/search?"
cmd = "curl -s -k -H \"Accept: yaml\" \"#{puppet_base}#{path}\""
ans = %x[#{cmd}]
nodes = YAML::load(ans)
nodes.sort.each do |node|
	node_url="https://puppet:8140/production/facts/#{node}"
	node_cmd="curl -s -k -H \"Accept: yaml\" #{node_url}"
	node_ans= %x[#{node_cmd}]
	output=File.new('out.yml','a')
        output.puts node_ans
        output.close
end
